from __future__ import annotations

from .tlic_models import BranchOptions, BranchResult


def build_python_script(options: BranchOptions, result: BranchResult, include_sequence: bool) -> str:
    # Build a plain-text script that can be pasted/run in a PSS/E-style
    # automation environment.
    #
    # Important: ratings exported here are MVA values derived from the
    # result.current_rate_* amp fields through BranchResult helper methods.
    status = 1 if options.in_service else 0
    lines = [
        "# python automation script",
        "# auto generated by TLIC python port",
        f"# {options.line_name} line params",
        f"bus1 = {options.bus1}  # {options.bus1_name}",
        f"bus2 = {options.bus2}  # {options.bus2_name}",
        f"ckt = '{options.ckt}'",
        f"status = {status}",
        f"r1 = {result.r1_pu:.6f}",
        f"x1 = {result.x1_pu:.6f}",
        f"b1 = {result.b1_pu:.6f}",
    ]
    if include_sequence:
        lines.extend(
            [
                f"r0 = {result.r0_pu:.6f}",
                f"x0 = {result.x0_pu:.6f}",
                f"b0 = {result.b0_pu:.6f}",
            ]
        )

    lines.extend(
        [
            f"A = {result.mva_rating_a(options.kv):.2f}",
            f"B = {result.mva_rating_b(options.kv):.2f}",
            f"C = {result.mva_rating_c(options.kv):.2f}",
            f"mile = {result.length_mi:.4f}",
            "",
            "# load data into case:",
            "psspy.branch_data(bus1,bus2,ckt,[status,_i,_i,_i,_i,_i,_i],[r1,x1,b1,A,B,C,_f,_f,_f,_f,_f,_f,mile,_f,_f,_f,_f])",
        ]
    )

    if include_sequence:
        lines.append("psspy.seq_branch_data(bus1,bus2,ckt,[r0,x0,b0,_f,_f,_f,_f])")

    return "\n".join(lines) + "\n"


def build_aux_script(options: BranchOptions, result: BranchResult) -> str:
    # Build a PowerWorld AUX payload with one branch row.
    # This mirrors the Main tab’s final solved values at export time.
    status = '"Closed"' if options.in_service else '"Open"'
    return "\n".join(
        [
            "// AUX automation script",
            "// auto generated by TLIC python port",
            "DATA (Branch, [BusNum,BusNum:1,LineCircuit,LineStatus,LineLength,BranchDeviceType,LineXfmr,",
            "LineR,LineX,LineC,LineMVA,LineMVA:1,LineMVA:2], YES)",
            "{",
            f"\t{options.bus1} {options.bus2} \"{options.ckt}\" {status} {result.length_mi:.6f} \"Line\" \"NO\" "
            f"{result.r1_pu:.6f} {result.x1_pu:.6f} {result.b1_pu:.6f} "
            f"{result.mva_rating_a(options.kv):.2f} {result.mva_rating_b(options.kv):.2f} {result.mva_rating_c(options.kv):.2f} "
            f"// \"{options.bus1_name}\" \"{options.bus2_name}\"",
            "}",
            "",
        ]
    )
